### ISSUE TITLE
Sync AKS ScaledObject with host.json

### ISSUE THREAD

**Issue by marcd123** [microsoft/durabletask-mssql#42]
I have the following configuration in my host.json file to control my Function App's `maxConcurrentOrchestratorFunctions` and `maxConcurrentActivityFunctions` limits:

```
"extensions": {
    "durableTask": {
      "maxConcurrentOrchestratorFunctions": 2,
      "maxConcurrentActivityFunctions": 2,
      "storageProvider": {
        "type": "mssql",
        "connectionStringName": "SQLDB_Connection",
        "taskEventLockTimeout": "00:02:00",
        "partitionCount": 3
      }
    }
  }
```

When I generate my deployment using `func kubernetes deploy` it creates a ScaledObject for me with the `GetScaleRecommendation` function setup, however the function parameters are out of sync with my host.json file. 

I would expect the parameters to line up with my host.json settings like `SELECT dt.GetScaleRecommendation(2, 2)` though instead I get this ScaledObject configuration:

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: bat-artwork-review-api
  labels: {}
spec:
  scaleTargetRef:
    name: bat-artwork-review-api
  triggers:
  - type: mssql
    metadata:
      query: SELECT dt.GetScaleRecommendation(10, 1)
      targetValue: "1"
      connectionStringFromEnv: SQLDB_Connection
```

Is there any way to sync these parameters currently?

**Comment by marcd123** [comment]
Is there any solution for this?

Our current solution is to do a deployment using `func kubernetes deploy` which deploys the ScaledObject above with these settings `SELECT dt.GetScaleRecommendation(10, 1)`

Then we manually deploy another ScaledObject with the same name but different settings to overwrite the previous one:

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: bat-artwork-review-api
  labels: {}
spec:
  scaleTargetRef:
    name: bat-artwork-review-api
  triggers:
  - type: mssql
    metadata:
      query: SELECT dt.GetScaleRecommendation(2, 2)
      targetValue: "1"
      connectionStringFromEnv: SQLDB_Connection
```
